#!/bin/bash
#if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
#    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
#fi
### BEGIN INIT INFO
# Provides:          ramdisk
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ramdisk
# Description:       Ramdisk
### END INIT INFO

# Author: Michal Subrt <spekodlak@gmail.com>

dir_config="/etc/ramdisk/ramdisk.conf"
tmpfs="/dev/shm"
unionfs="aufs"
rsync="rsync -auc --delete-delay"

config () {
  readarray -t dirs < "$dir_config"
  tmpfs=${tmpfs%/}
}

do_start () {
  config
  for p in "${dirs[@]}"; do
    path="${p%/}"
    mkdir -p "${tmpfs}${path}"
    $rsync "${path}/" "${tmpfs}${path}/"
    mount -t "$unionfs" -o dirs="${tmpfs}${path}":"${path}" none "${path}"
  done
}

do_stop () {
  config
  for p in "${dirs[@]}"; do
    path="${p%/}"
    umount "${path}"
    $rsync "${tmpfs}${path}/" "${path}/"
    rm -r "${tmpfs}${path}" \
        "${path}/.wh..wh.aufs" \
        "${path}/.wh..wh.orph" \
        "${path}/.wh..wh.plnk"
  done

  for p in "${dirs[@]}"; do
    path="${p%/}"
    rm -rf "${tmpfs}/`echo ${path} | cut -d "/" -f2`"
  done
}

do_restart () {
  do_stop
  do_start
}

case "$1" in
  start)
        do_start
	;;
  reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  stop)
	do_restart
	;;
  status)
	exit 0
	;;
  *)
	echo "Usage: $0 start|stop|restart" >&2
	exit 3
	;;
esac
