#!/bin/bash
# Author: Michal Subrt <spekodlak@gmail.com>

dir_config="/etc/ramdisk/ramdisk.conf"
rsync="rsync -aucv --delete-delay"

do_config () {
  readarray -t dirs < "$dir_config"
}

do_backup () {
  do_config
  for p in "${dirs[@]}"; do
    path="${p%/}"
    mkdir -pv "${path}.backup"
    $rsync "${path}/" "${path}.backup/"
  done
}

do_symlink() {
  do_config
  for p in "${dirs[@]}"; do
    path="${p%/}"
    rm -rv "${path}"
    ln -sv "${path}.backup" "${path}"
  done
}

do_restore_backup () {
  do_config
  for p in "${dirs[@]}"; do
    path="${p%/}"
    rm -v "${path}"
    mkdir -pv "${path}"
    $rsync "${path}.backup/" "${path}/"
  done
}

do_load_tmpfs () {
  do_config
  for p in "${dirs[@]}"; do
    path="${p%/}"
    $rsync "${path}.backup/" "${path}/"
  done
}

do_clean () {
  do_config
  for p in "${dirs[@]}"; do
    path="${p%/}"
    rm -rv "${path}.backup"
  done
}

case "$1" in
  backup)
        do_backup
	;;
  simlink)
        do_symlink
	;;
  restore-backup)
	do_restore_backup
	;;
  load-tmpfs)
	do_load_tmpfs
	;;
  clean)
	do_clean
	;;
  *)
	echo "Usage: $0 backup|simlink|restore|clean" >&2
	exit 3
	;;
esac
